# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.CharField(blank=True, max_length=6, null=True)),
                ('a_val', models.PositiveIntegerField(blank=True, null=True)),
                ('q_val', models.PositiveIntegerField(blank=True, null=True)),
                ('q_dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('q_set', models.PositiveIntegerField(blank=True, null=True)),
                ('q_index', models.PositiveIntegerField(blank=True, null=True)),
                ('a_page_loaded', models.CharField(blank=True, max_length=255, null=True)),
                ('a_start_time', models.CharField(blank=True, max_length=255, null=True)),
                ('a_submit_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(max_length=255)),
                ('q_dimension', models.CharField(max_length=255)),
                ('q_set', models.PositiveIntegerField()),
                ('q_index', models.PositiveIntegerField()),
                ('q_min', models.PositiveIntegerField()),
                ('q_max', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='q',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcoding_1d.Question'),
        ),
    ]
