# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcoding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_title',
        ),
    ]
