# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcoding', '0002_auto_20180225_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='q_val',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
