# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcoding', '0004_auto_20180226_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a_val',
            field=models.PositiveIntegerField(),
        ),
    ]
