# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcoding', '0006_auto_20180308_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='a_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
